on:
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create .venv folder
        run: mkdir ~/projects/actions-runner/_work/lemon/lemon/venv
      - name: Create virtual environment
        run: python -m venv ~/projects/actions-runner/_work/lemon/lemon/venv
      - name: Activate virtual environment
        run: source ~/projects/actions-runner/_work/lemon/lemon/venv/bin/activate
      - name: Add packages from requirements.txt
        run: /home/berry/projects/actions-runner/_work/lemon/lemon/venv/bin/pip install -r ~/projects/actions-runner/_work/lemon/lemon/requirements.txt
      - name: Run the webserver
        run: /home/berry/projects/actions-runner/_work/lemon/lemon/venv/bin/python ~/projects/actions-runner/_work/lemon/lemon/manage.py runserver > /dev/null 2>&1 &
      - name: Connect with reverse proxy
        run: (cd ~/projects/pi_home_reverse_proxy  && make connect) > /dev/null 2>&1 & 
        
